### ISSUE TITLE
Hide Cells in the Notebook History Viewer

### ISSUE THREAD

**Issue by acrule** [acrule/janus#16]
Right now the history viewer does not reflect which cells are hidden in the notebook. We should be able to run the same code we use in the main notebook to create "placeholders" for hidden cells, and even enable hidden cell preview using a detailed tooltip, but I don't think we want users to be able to click these placeholders to open the cells in an embedded sidebar.

**Comment by wddlz** [comment]
have the code to hide the cells but generating placeholders does not work by calling current functions, tbd

**Comment by acrule** [comment]
Now going to work on hiding portions of cells with hidden code or hidden output. Also will need to see if there is a way for us to assign proper names to the groups of hidden cells. Right now I am just defaulting everything to "Hidden Cells". We could look at the most recent arrangement of hidden cells and get the names from those groupings, but this will not reflect changes to group names over time.

**Comment by acrule** [comment]
The last thing to fix is getting a name for the hidden cell markers. For now we default everything to "Hidden Cells". Fixing this would involve tracking changes to hidden cell names over time, which is a larger feature, so closing this issue for now.
