### ISSUE TITLE
Float History Viewer scrollbar

### ISSUE THREAD

**Issue by acrule** [acrule/janus#17]
Right now it is hard to use the scrollbar if you want to look at changes that occur near the end of the notebook. We could float the scrollbar so users can look at a later part of the notebook but still have the scrollbar be visible so they can scroll back and forth to see the changes there

**Comment by wddlz** [comment]
3aae53c

**Comment by acrule** [comment]
We want it so moving the slider does not cause the user to scroll all the way to the top of the notebook. I think we can do something like check their current scroll height, render the cells, and then set scroll height to the min of either the previous scroll height or current length.
