### ISSUE TITLE
Enable multiple sidebars to be open at once

### ISSUE THREAD

**Issue by acrule** [acrule/janus#28]
This will be a significant rewrite, but we should consider letting users have multiple sidebars open at once. Imagine an interaction similar to Google Docs Comments where we can stack each of the sidebars and move them up or down based on what the user selects. Users should be able to:
- open and close individual sidebars by clicking on hidden cell, code, and output markers
- move between sidebars by clicking on them
- sidebars should dynamicly move up and down based on what other sidebars are in focus

**Comment by wddlz** [comment]
1. Create sidebar container
2. Add titles for sidebars
3. Collapse button to sidebars
4. Stack multiple sidebars (multiple open at once)
5. Position sidebars dynamically 
6. Anchor clicked (selected) cell and referential sidebar

**Comment by acrule** [comment]
We now have working code for 1. I'll start working on 3 and 4 this afternoon. 4 will likely be messy since a lot of the code was written assuming there was one sidebar, and often checked sidebar.cells. We will need to instead iterate through all "sections" in the sidebar to see if their list of cells match what we are looking for (e.g., as when checking to see if we are trying to render a new section, or just rerendering an old one.

**Comment by acrule** [comment]
Can now show multiple sections of hidden cells in the sidebar. Now need to work on a more intelligent way to link the sidebars and the placeholders for groups of hidden cells. We need to make sure that when a cell is moved hidden or shown in a way that should affect a group of hidden cells shown in the sidebar, that the appropraite section of the sidebar updates.

**Comment by acrule** [comment]
Right now the process of managing and updating sections in the sidebar is very distributed (we destroy all the sidebar sections and all the hidden cell markers in the main notebook, re-render them, and use data stored on the hidden marker DOM elements to determine if we should re-render the elements again. This happens every time a cell is moved, hidden/shown, copy, pasted... essentially everytime something happens that could impact the sidebar or the main notebook. I think we will want to move towards a more centralized model that stores information in a central object (either under Jupyter.notebook.metadata.janus.janus_markers, or a new Jupyter.sidebar.markers object) and only updates when needed (e.g. check if the action actually affected any hidden cells and only update the hidden cell markers and the sidebar sections that are affected.

**Comment by acrule** [comment]
Okay, I have taken care of items 1-4 in a rather roundabout way. We should look into positioning, and also if there is a more straightforward and scalable way to get the same functionality.

**Comment by wddlz** [comment]
working on positioning now > For selected being highlight or brought "forward" (inline with matching cell) I think it will mostly hinge on getting the position of the clicked (Ypos) and matching it with the matching cell. and for 5 I'll just try +/-% of new

**Comment by acrule** [comment]
Rather than determine which cell was clicked based on the y-position of the click event, I think you can just intercept the click event that occurs on the hidden cell markers or on the sidebar sections and get the cell from there. I'm also wondering if we actually will want to use different CSS to aid positioning. Right now *I think* the sidebar container wrapping all sidebar sections is positioned absolutely, and the cell sections are just floated one after the other within it. Would it be better for the sidebar simply to be a large div with min-height set to the same height as the main notebook and we position each section separately and absolutely within that? Not sure.

**Comment by wddlz** [comment]
We can also just look at the order of the main nb and then iterate through sidebar and through a no delete splices insert the new sidebar object into the right place (either by assigning position to all cells in nb (like 0,1,2,3,4,etc.) or by comparing main with side(n^2 loop)). 

Problem I'm having is figuring out where this order is maintained. I've changed a few pushes (in both opensection and rendercells) to splice(index,0,newsb) but it doesn't have any effect, so I'm not sure if these functions are where I can control order of the presentation.

**Comment by wddlz** [comment]
or maybe https://jqueryui.com/draggable/#sortable ?

**Comment by acrule** [comment]
I don't think the draggable will work quite like we want. I think we have 2 issues.

1. We would like the Sidebar divs to be in the correct order in the DOM (e.g., if one sidebar section div represents cells hidden at the top of the notebook, it should come before a section div that represents cells hidden further down in the notebook, at least in the DOM.) I think we can approach this issue by creating JavaScript objects for both the hidden cell placeholders in the main notebook, and the sidebar sections. These can link to one another enabling us to easily check if a sidebar section we are creating should go before or after any other sections already shown in the sidebar. Then we can just use jquery's .after function to insert them in the correct place in the DOM.

2. Dynamically positioning those elements to get an interaction like that afforded by Google Docs' comments will be slightly tricky, but doable. Google simply uses absolute positioning to move the divs around and my guess is there is just some logic in the background that first positions the selected comment, and then checks to see if any of the other comments need to be moved as well to make room. I think this will be a fairly straightforward matter of calculating sidebar section y position and heights and iterating backward and forward from the selected sidebar section to move any of the others out of the way. 

Also see my recent email. I think we may want to whiteboard the interaction together in person so we are on the same page.
