### ISSUE TITLE
Issue running janus for the first time

### ISSUE THREAD

**Issue by aurelient** [acrule/janus#35]
Hi, 
I've been trying to run Janus but there seems to be some dependency issue.
I've followed the README to install Janus.

`TypeError: Jupyter.notebook.metadata.janus is undefined
Stack trace:
updateHistoryUI@http://localhost:8888/nbextensions/janus/history.js?v=20180301162051:158:13
renderJanusButtons@http://localhost:8888/nbextensions/janus/ui.js?v=20180301162051:206:9
renderJanusUI@http://localhost:8888/nbextensions/janus/ui.js?v=20180301162051:216:9
loadExtension@http://localhost:8888/nbextensions/janus/main.js?v=20180301162051:56:9
load_extension/</<@http://localhost:8888/static/notebook/js/main.min.js?v=6a166b31c5a20f809e44ec2d50e40412:12408:41
execCb@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1690:24
check@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:865:43
enable/</<@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1140:29
bind/<@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:131:20
emit/<@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1190:21
each@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:56:31
emit@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1189:17
check@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:940:25
enable/</<@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1140:29
bind/<@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:131:20
emit/<@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1190:21
each@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:56:31
emit@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1189:17
check@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:940:25
enable/</<@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1140:29
bind/<@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:131:20
emit/<@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1190:21
each@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:56:31
emit@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1189:17
check@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:940:25
enable/</<@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1140:29
bind/<@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:131:20
emit/<@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1190:21
each@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:56:31
emit@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1189:17
check@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:940:25
enable@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1177:17
init@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:783:21
callGetModule@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1204:17
completeLoad@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1583:21
onScriptLoad@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1711:21
 require.js:900:37
`

**Comment by aurelient** [comment]
This is the notebook I was working on.
http://nbviewer.jupyter.org/github/AmigoCap/CampusFlow/blob/master/02-Donn%C3%A9es_Test.ipynb

**Comment by acrule** [comment]
Sorry about that. Should be fixed now. Had implemented a feature that required having metadata that had not been initialized yet.

**Comment by aurelient** [comment]
It works now. Thanks!
